pin SQLAlchemy to <2.1 to fix AmbiguousColumnError
sqlalchemy.exc.AmbiguousColumnError: Attribute name "languoid_id" is ambiguous;
it exists in multiple FROM clause entities (link, Mapper[Link(link)]).
Use filter() with explicit column references instead of filter_by().

https://docs.sqlalchemy.org/en/21/changelog/migration_21.html#ambiguous-attribute-names